class Tourniquet < Formula
  include Language::Python::Virtualenv

  desc "Anthropic API proxy with hard daily spend caps — local-first"
  homepage "https://tourniquet.dev"
  url "https://files.pythonhosted.org/packages/source/t/tourniquet-dev/tourniquet_dev-0.1.0.tar.gz"
  sha256 "fa2a48f5addd6540ce7a54d3929769fee8e2231b3b44cd5b30cc4c7e74cfeaef"
  license "MIT"

  depends_on "python@3.12"

  # Resources are auto-generated by `brew update-python-resources tourniquet`
  # after publishing to PyPI. The starter list below covers the core deps.
  resource "fastapi" do
    url "https://files.pythonhosted.org/packages/source/f/fastapi/fastapi-0.115.0.tar.gz"
    sha256 "REPLACE_WITH_SHA256"
  end

  # ... (run `poet -f tourniquet >> Formula.rb` or `brew update-python-resources` to fill in)

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "tourniquet 0.1.0", shell_output("#{bin}/tourniquet --version")
  end
end

# To publish:
#   1. Publish tourniquet to PyPI:  python -m build && twine upload dist/*
#   2. Get sha256 of the tarball:   shasum -a 256 dist/tourniquet-0.1.0.tar.gz
#   3. Replace REPLACE_WITH_SHA256_AFTER_PYPI_UPLOAD above
#   4. Run `brew update-python-resources tourniquet` to fill in `resource` blocks
#   5. Push to github.com/LowryDaniel/homebrew-tourniquet (a tap repo)
#   6. Users install with: brew install LowryDaniel/tourniquet/tourniquet
